### PR TITLE
Add save! to Jira Sprint resource

### PR DESCRIPTION
**Pull request by shirish-pampoorickal**
@ahuth @eihli Appreciate a look

cc @adambedford

### CODE REVIEW

**Comment by ahuth** [comment]
Looks like we've diverged a little bit from the forked gem. Any chance that switching back to the original would get us what we need, @shirish-pampoorickal ?

**Comment by adambedford** [comment]
@ahuth We have diverged a little, and we're taking the better path (using Jira's new Agile API) so the plan is to contribute back to upstream at some point in the near future.

**Comment by ahuth** [comment]
Makes sense. Thanks @adambedford.

LGTM :metal:

**Comment by eihli** [comment]
LGTM

**Pull request merged**
